//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsVer2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentImage
    {
        public int ID { get; set; }
        public int ImageID { get; set; }
        public int StudentID { get; set; }
    
        public virtual ImageDocument ImageDocument { get; set; }
        public virtual Student Student { get; set; }
    }
}
